sudo: false
language: python
services:
- memcached
- postgresql
- redis-server
python:
- '2.7'
cache:
  directories:
  - node_modules
  - "$HOME/.cache/pip"
deploy:
  - provider: pypi
    server: https://test.pypi.org/legacy/
    user: max-wittig
    password:
      secure: "NOcuIVrhvSQIFE0oeCvI2AOH2tSSmUoQqDPiGt0SMf9K2j0QMeQznycrIxCK9kztTPyWvr0gS2Ntrpem9FEGLUH+48U7TcOvRx4QH/pl50Oo5Yslfgi3F8zIUUeTp4h4/UAK4kLm+65tHSBSE4bnFlXtPqDpqumDuTLhd+gimTRT+/tq/wxkEEr3yUaH2z3fTxatpis3npTbVVwDIvN3avE3ogOKBIfal/z24ppZohzqRtxXhKK8cgCpS3sz8HhOGlGCNvexCV1hkY3X+hKvVevbM8hQJW61sQk8XUzzg+zAjE+lEcijOMV22kruAUT99RSnhW2MXr3ibuBLvS8fS+OfyTI47i5/MHcjxrfXcdM94AwuiQItGvDmfWopZG6RHuSP11IZ4no/rd8ZvbsgP3v4gTpubUC7y9EwSy6RbIJEAYlvzO6D+fiXsq34N1lWWu1WtbN3yRraI+WsrX3eCHH/x52UjyNbNShS7hsUdU/ohQwaMjsnUPlAytV9e+Jk5PBLUS/Li6VhQ4ljlbVZYALymxlepmOY41BPfnhNDf/OrQ21qMOuCCpMA8grLDKE6O9qfSi29rHuG7/6LWfgA/3JcvjXBuk7EbQinZ28wiBwKEd2trEzKlacQKhEjXY0TkTUmYnG98NVBdgCiFVDrrg8BCeSHRhQ4cgQrElvWAs="
    distributions: sdist bdist_wheel
    on:
      all_branches: true
env:
  global:
  - PIP_DOWNLOAD_CACHE=".pip_download_cache"
  - PIP_DISABLE_PIP_VERSION_CHECK=on
  - SENTRY_SKIP_BACKEND_VALIDATION=1
before_install:
- pip install codecov
- pip install -U setuptools
install:
- make develop
script:
- PYFLAKES_NODOCTEST=1 flake8
- coverage run --source=. -m py.test tests
after_success:
- codecov
